# codecov.yml
codecov:
  removed_code_behavior: adjust_base # <-- ADD THIS SECTION

component_management:
  individual_components:
    - component_id: core_logic
      name: Core Logic
      paths: 
        # Target only your main implementation file
        - Cal.go 

comment:
  # This makes the component breakdown show up in the Pull Request comment
  layout: "header, diff, flags, components"
