# codecov.yml
codecov:
  removed_code_behavior: adjust_base 

component_management:
  individual_components:
    - component_id: core_logic  # <-- This line needs four spaces before the dash
      name: Core Logic        # <-- This line needs six spaces
      paths:                  # <-- This line needs six spaces
        # Target only your main implementation file
        - Cal.go              # <-- This line needs six spaces before the dash

comment:
  # This makes the component breakdown show up in the Pull Request comment
  layout: "header, diff, flags, components"

status:
  # Global project coverage must be at least 90%
  project:
    default:
      target: 90%
  
  # Override for the critical 'core_logic' component
  components:
    core_logic:
      target: 95% # <-- The minimum target for Cal.go and related files

# ... rest of your file (component_management, comment, etc.)
