# codecov.yml
component_management:
  individual_components:
    - component_id: core_logic
      name: Core Logic
      paths: 
        # Target only your main implementation file
        - Cal.go 
        # You can exclude the test file or simply rely on the 'unittests' flag
        # - !cal_test.go 

comment:
  # This makes the component breakdown show up in the Pull Request comment
  layout: "header, diff, flags, components"
